import type { Metadata } from 'next'

import './globals.css'
import { ReactNode } from 'react'
import Header from '@/components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function StoreLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body className='mx-auto grid min-h-screen w-full max-w-[1600px] grid-rows-[min-content_max-content]'>
        <Header />
        {children}
      </body>
    </html>
  )
}
